/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0Yv84rpcOyd
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Inter } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
**/
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select";
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group";
import { Button } from "@/components/ui/button";
import { createProduct } from "@/services/product/product-service";

export function CreateProductForm() {
  return (
    <form action={createProduct} className="w-full max-w-2xl">
      <Card>
        <CardHeader>
          <CardTitle>Create New Product</CardTitle>
          <CardDescription>Fill out the form to add a new product.</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="grid gap-2">
              <Label htmlFor="title">Title</Label>
              <Input id="title" name="title" placeholder="Product Title" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="price">Price</Label>
              <Input id="price" name="price" placeholder="99.99" type="number" />
            </div>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="description">Description</Label>
            <Textarea className="min-h-[100px]" id="description" name="description" placeholder="Describe your product" />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="grid gap-2">
              <Label htmlFor="category">Category</Label>
              <Select name="category">
                <SelectTrigger>
                  <SelectValue placeholder="Select Category" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="rustic elegance">Rustic Elegance</SelectItem>
                  <SelectItem value="mystic garden">Mystic Garden</SelectItem>
                  <SelectItem value="sunrise symphony">Sunrise Symphony</SelectItem>
                  <SelectItem value="whispering earth">Whispering Earth</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="title">Image</Label>
              <Input id="image" name="image" placeholder="Product Image URL" />
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="grid gap-2">
              <Label htmlFor="stock">Stock Quantity</Label>
              <Input id="stock" name="stock" placeholder="100" type="number" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="size">Size</Label>
              <RadioGroup className="flex flex-wrap gap-2" name="size" id="size">
                <Label className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800" htmlFor="size-s">
                  <RadioGroupItem id="size-s" value="small" />S
                </Label>
                <Label className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800" htmlFor="size-m">
                  <RadioGroupItem id="size-m" value="medium" />M
                </Label>
                <Label className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800" htmlFor="size-l">
                  <RadioGroupItem id="size-l" value="large" />L
                </Label>
              </RadioGroup>
            </div>
          </div>
        </CardContent>
        <CardFooter className="justify-end">
          <Button className="w-full md:w-auto" type="submit">
            Save Product
          </Button>
        </CardFooter>
      </Card>
    </form>
  );
}
